### PR TITLE
Remove pymongo

### PR DESCRIPTION
**Pull request by philipcristiano**
#### Improvement

It isn't used. There are still references in the code to Mongo things,
but the pymongo code was imported and never used

### Tests

- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

#### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### CODE REVIEW

**Review by yawhide — COMMENTED** [review]
you gotta run poetry lock i believe

**Review by yawhide — APPROVED** [review]

**Comment by yawhide** [comment]
@philipcristiano also while you are there, can you update the other dependencies?

i think you can just run `poetry update`

**Comment by philipcristiano** [comment]
There is no lockfile https://github.com/coin-tracker/coinbasepro-python/commit/c729f7d2b70e446b80904d027c20cadb4a53a758 For libraries it's generally advised to not lock versions. That should be done by the "final" python project that uses everything. Locking in each lib makes it very difficult to upgrade other things.

**Comment by philipcristiano** [comment]
@yawhide I updated the version, after merging do you mind releasing to pypi?

**Comment by yawhide** [comment]
> @yawhide I updated the version, after merging do you mind releasing to pypi?

gotta remember how to do that lol

**Pull request merged**
